### ISSUE TITLE
find example repository

### ISSUE THREAD

**Issue by hannesdatta** [course-dprep/team-assignment-team-2#2]
example repos on analyzing impact of events on airbnb supply & demand

possible dimensions:
- more cities
- different events
- more time coverage
- different way of deployment (e.g., pdf report vs app vs...)

if you can't find the example, be in touch w/ @hannesdatta - use whatsapp

**Comment by carolinebloemendaal** [comment]
We discussed the topic: Most appealing cities in the US to rent an Airbnb during the week

We will analyse data from the top 10 cities in the US and compare them to price. We found an article which states that there is an upcoming trend in the US regarding the demand of Airbnb apartments during the week. Our data will confirm or reject this statement.
